services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - dock-net
    restart: unless-stopped

networks:
  dock-net:
    driver: bridge

volumes:
  postgres:



